name: Radicale
version: "0.3.3"
slug: radicale
description: Lightweight CalDAV and CardDAV server for Home Assistant
url: https://github.com/njharrison/home-assistant-radicale
arch:
  - aarch64
  - amd64
startup: services
boot: auto
init: false
webui: "https://[HOST]:[PORT:5232]/"
ports:
  5232/tcp: 5232
ports_description:
  5232/tcp: Radicale CalDAV/CardDAV HTTPS
options:
  username: homeassistant
  password: ""
  domain: "harrison-household.duckdns.org"
  duckdns_token: ""
schema:
  username: str
  password: password
  domain: str
  duckdns_token: password
